import { Location } from "@/core/domain/models/location";

export const mockLocations: Location[] = [
  { id: "1", value: "sao-paulo", label: "São Paulo, SP" },
  { id: "2", value: "rio-de-janeiro", label: "Rio de Janeiro, RJ" },
  { id: "3", value: "belo-horizonte", label: "Belo Horizonte, MG" },
  { id: "4", value: "salvador", label: "Salvador, BA" },
  { id: "5", value: "brasilia", label: "Brasília, DF" },
  { id: "6", value: "fortaleza", label: "Fortaleza, CE" },
  { id: "7", value: "manaus", label: "Manaus, AM" },
  { id: "8", value: "curitiba", label: "Curitiba, PR" },
  { id: "9", value: "recife", label: "Recife, PE" },
  { id: "10", value: "porto-alegre", label: "Porto Alegre, RS" },
  { id: "11", value: "belem", label: "Belém, PA" },
  { id: "12", value: "goiania", label: "Goiânia, GO" },
  { id: "13", value: "guarulhos", label: "Guarulhos, SP" },
  { id: "14", value: "campinas", label: "Campinas, SP" },
  { id: "15", value: "sao-luis", label: "São Luís, MA" },
  { id: "16", value: "sao-goncalo", label: "São Gonçalo, RJ" },
  { id: "17", value: "maceio", label: "Maceió, AL" },
  { id: "18", value: "duque-de-caxias", label: "Duque de Caxias, RJ" },
  { id: "19", value: "natal", label: "Natal, RN" },
  { id: "20", value: "teresina", label: "Teresina, PI" },
  { id: "21", value: "campo-grande", label: "Campo Grande, MS" },
  { id: "22", value: "sao-bernardo", label: "São Bernardo do Campo, SP" },
  { id: "23", value: "nova-iguacu", label: "Nova Iguaçu, RJ" },
  { id: "24", value: "joao-pessoa", label: "João Pessoa, PB" },
  { id: "25", value: "santo-andre", label: "Santo André, SP" },
  { id: "26", value: "osasco", label: "Osasco, SP" },
  { id: "27", value: "jaboatao", label: "Jaboatão dos Guararapes, PE" },
  { id: "28", value: "sao-jose-campos", label: "São José dos Campos, SP" },
  { id: "29", value: "ribeirao-preto", label: "Ribeirão Preto, SP" },
  { id: "30", value: "uberlandia", label: "Uberlândia, MG" },
  { id: "31", value: "sorocaba", label: "Sorocaba, SP" },
  { id: "32", value: "contagem", label: "Contagem, MG" },
  { id: "33", value: "aracaju", label: "Aracaju, SE" },
  { id: "34", value: "feira-santana", label: "Feira de Santana, BA" },
  { id: "35", value: "cuiaba", label: "Cuiabá, MT" },
  { id: "36", value: "joinville", label: "Joinville, SC" },
  { id: "37", value: "juiz-fora", label: "Juiz de Fora, MG" },
  { id: "38", value: "londrina", label: "Londrina, PR" },
  { id: "39", value: "aparecida-goiania", label: "Aparecida de Goiânia, GO" },
  { id: "40", value: "porto-velho", label: "Porto Velho, RO" },
  { id: "41", value: "ananindeua", label: "Ananindeua, PA" },
  { id: "42", value: "serra", label: "Serra, ES" },
  { id: "43", value: "niteroi", label: "Niterói, RJ" },
  { id: "44", value: "vitoria", label: "Vitória, ES" },
  { id: "45", value: "macapa", label: "Macapá, AP" },
  { id: "46", value: "florianopolis", label: "Florianópolis, SC" },
  { id: "47", value: "sao-joao-meriti", label: "São João de Meriti, RJ" },
  { id: "48", value: "mogi-cruzes", label: "Mogi das Cruzes, SP" },
  { id: "49", value: "diadema", label: "Diadema, SP" },
  { id: "50", value: "betim", label: "Betim, MG" },
  { id: "51", value: "carapicuiba", label: "Carapicuíba, SP" },
  { id: "52", value: "olinda", label: "Olinda, PE" },
  { id: "53", value: "campina-grande", label: "Campina Grande, PB" },
  { id: "54", value: "piracicaba", label: "Piracicaba, SP" },
  { id: "55", value: "cariacica", label: "Cariacica, ES" },
  { id: "56", value: "bauru", label: "Bauru, SP" },
  { id: "57", value: "itaquaquecetuba", label: "Itaquaquecetuba, SP" },
  { id: "58", value: "sao-vicente", label: "São Vicente, SP" },
  { id: "59", value: "vitoria-conquista", label: "Vitória da Conquista, BA" },
  { id: "60", value: "caucaia", label: "Caucaia, CE" },
  { id: "61", value: "itabuna", label: "Itabuna, BA" },
  { id: "62", value: "maringa", label: "Maringá, PR" },
  { id: "63", value: "campos-goytacazes", label: "Campos dos Goytacazes, RJ" },
  { id: "64", value: "hortolandia", label: "Hortolândia, SP" },
  { id: "65", value: "presidente-prudente", label: "Presidente Prudente, SP" },
  { id: "66", value: "sao-leopoldo", label: "São Leopoldo, RS" },
  { id: "67", value: "guaruja", label: "Guarujá, SP" },
  { id: "68", value: "taubate", label: "Taubaté, SP" },
  { id: "69", value: "pelotas", label: "Pelotas, RS" },
  { id: "70", value: "praia-grande", label: "Praia Grande, SP" },
  { id: "71", value: "limeira", label: "Limeira, SP" },
  { id: "72", value: "santarem", label: "Santarém, PA" },
  { id: "73", value: "petrolina", label: "Petrolina, PE" },
  { id: "74", value: "blumenau", label: "Blumenau, SC" },
  { id: "75", value: "franca", label: "Franca, SP" },
  { id: "76", value: "caruaru", label: "Caruaru, PE" },
  { id: "77", value: "ponta-grossa", label: "Ponta Grossa, PR" },
  { id: "78", value: "vitoria-es", label: "Vitória, ES" },
  { id: "79", value: "guarapuava", label: "Guarapuava, PR" },
  { id: "80", value: "cascavel", label: "Cascavel, PR" },
  { id: "81", value: "ipatinga", label: "Ipatinga, MG" },
  { id: "82", value: "embu", label: "Embu das Artes, SP" },
  { id: "83", value: "vila-velha", label: "Vila Velha, ES" },
  { id: "84", value: "varzea-grande", label: "Várzea Grande, MT" },
  { id: "85", value: "santa-maria", label: "Santa Maria, RS" },
  {
    id: "86",
    value: "governador-valadares",
    label: "Governador Valadares, MG",
  },
  { id: "87", value: "sao-jose-rio-preto", label: "São José do Rio Preto, SP" },
  { id: "88", value: "novo-hamburgo", label: "Novo Hamburgo, RS" },
  { id: "89", value: "barueri", label: "Barueri, SP" },
  { id: "90", value: "viamao", label: "Viamão, RS" },
  { id: "91", value: "volta-redonda", label: "Volta Redonda, RJ" },
  { id: "92", value: "juazeiro-norte", label: "Juazeiro do Norte, CE" },
  { id: "93", value: "imperatriz", label: "Imperatriz, MA" },
  { id: "94", value: "taboao-serra", label: "Taboão da Serra, SP" },
  { id: "95", value: "sumare", label: "Sumaré, SP" },
  { id: "96", value: "palmas", label: "Palmas, TO" },
  { id: "97", value: "rio-branco", label: "Rio Branco, AC" },
  { id: "98", value: "boa-vista", label: "Boa Vista, RR" },
  { id: "99", value: "arapiraca", label: "Arapiraca, AL" },
  { id: "100", value: "maraba", label: "Marabá, PA" },
];
